### ISSUE TITLE
older node support?

### ISSUE THREAD

**Issue by apsoto** [eggplanetio/mert#15]
I happen to have an older node as my default and received this error.

Installing the latest node works great though.

```
/Users/asoto/.nvm/versions/node/v4.4.4/lib/node_modules/mert/lib/launcher.js:60
  let cmdCounter = 0;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/asoto/.nvm/versions/node/v4.4.4/lib/node_modules/mert/index.js:21:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by yaring** [comment]
I've the same error on node v5.9.1

```
/Users/yarin.goldman/.nvm/versions/node/v5.9.1/lib/node_modules/mert/lib/launcher.js:60
  let cmdCounter = 0;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/yarin.goldman/.nvm/versions/node/v5.9.1/lib/node_modules/mert/index.js:21:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by briangonzalez** [comment]
Sorry, but we're not going to backport to make this one work wth Node < 6.2.0

**Comment by LeonardoGentile** [comment]
Kind of extreme..I would have continued to user temrc in the meanwhile but it doesn't work anymore with the new iterm release..

**Comment by briangonzalez** [comment]
Sorry, I am not trying to be brash, but we only have limited time and maintaining older versions of node is not going to be sustainable in the long term.

Do you have hesitations with upgrading?

**Comment by LeonardoGentile** [comment]
Hi @briangonzalez I understand.
I have to handle older versions of node for some machines setup and would rather not to touch them. 

Thanks btw for the great work 👍
