### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by LeonardoGentile** [eggplanetio/mert#20]
Hello,
I'm on Mavericks, mert 0.7.1, node v6.3.1, iTerm Build 3.0.5.
I simply do `mert init` then `mert start`.  
The last command fails returning this:

```
/Users/me/.nvm/versions/node/v6.3.1/lib/node_modules/mert/lib/launcher.js:17
  return iterm.currentWindow().id();

TypeError: Cannot read property 'id' of undefined
    at newWindow (/Users/me/.nvm/versions/node/v6.3.1/lib/node_modules/mert/lib/launcher.js:17:31)
    at Object.launch (/Users/me/.nvm/versions/node/v6.3.1/lib/node_modules/mert/lib/launcher.js:93:16)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v6.3.1/lib/node_modules/mert/index.js:29:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
```

**Comment by briangonzalez** [comment]
@LeonardoGentile You still experiencing this issue?

**Comment by paxperscientiam** [comment]
I too am experiencing this.

**Comment by LeonardoGentile** [comment]
@briangonzalez I've upgraded to El Capitan and it seems to work with the same settings and versions of node and iterm as above..not sure why.

I've also tested on another machine running El Capitan, using iTerm Build 3.0.8 and node v6.3.0 and it works.

So it seems the problem is related to the Os Version

**Comment by briangonzalez** [comment]
@paxperscientiam you experiencing this issue on mavericks as well?

**Comment by theverything** [comment]
I have this issue too.
- OS X El Capitan 10.11.6
- iTerm2 Build 3.0.8
- Mert 0.8.0
- Node 6.5.0
- npm 3.10.3

```
/usr/local/lib/node_modules/mert/lib/launcher.js:17
  return iterm.currentWindow().id();
                               ^

TypeError: iterm.currentWindow(...).id is not a function
    at newWindow (/usr/local/lib/node_modules/mert/lib/launcher.js:17:32)
    at Object.launch (/usr/local/lib/node_modules/mert/lib/launcher.js:93:16)

# or

/usr/local/lib/node_modules/mert/lib/launcher.js:47
  windowId = windowId || iterm.currentWindow().id();
                                               ^

TypeError: iterm.currentWindow(...).id is not a function
    at buildLayout (/usr/local/lib/node_modules/mert/lib/launcher.js:47:48)
    at Object.launch (/usr/local/lib/node_modules/mert/lib/launcher.js:99:5)

# or

/usr/local/lib/node_modules/mert/lib/launcher.js:21
  windowId = windowId || iterm.currentWindow().id();
                                               ^

TypeError: iterm.currentWindow(...).id is not a function
    at newTab (/usr/local/lib/node_modules/mert/lib/launcher.js:21:48)
    at Object.launch (/usr/local/lib/node_modules/mert/lib/launcher.js:91:5)

# the rest of the stack trace

    at Object.<anonymous> (/usr/local/lib/node_modules/mert/index.js:30:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
```

**Comment by briangonzalez** [comment]
@theverything I have this exact setup. Can you send me your mertrc?

**Comment by schmurfy** [comment]
I wanted to try this project and got the same error as above.
node 7.1.0
npm 3.10.9
mert 0.8.0

**Comment by briangonzalez** [comment]
@schmurfy Can you please provide your mertrc file?

**Comment by schmurfy** [comment]
Here is what `mert init`created:

```yaml
root: "~"
layout:
  -
    - echo "Row 1, Pane 1"
  -
    - echo "Row 2, Pane 1"
    - echo "Row 2, Pane 2"
  -
    - echo "Row 3, Pane 1"
    - echo "Row 3, Pane 2"
    - echo "Row 3, Pane 3"

```

**Comment by paxperscientiam** [comment]
@briangonzalez I am on OSX 10.12 and I'm getting the same error. I then uninstalled and re-installed. Same error :/

**Comment by paxperscientiam** [comment]
bump

**Comment by briangonzalez** [comment]
I'll try to take a look this week!

**Comment by travsten** [comment]
Any word on this?? Still problem for me.

**Comment by briangonzalez** [comment]
Mind trying the following? @travsten 

1. First open up iTerm.
2. Clone Mert.
```sh
git clone git@github.com:eggplanetio/mert.git
cd mert
node
```

3. Try to grab ID of open iTerm window in node

```js
// now from within node.....
const jxa = require('jxa');
const Application = jxa.Application;
const iterm = Application('iTerm');
iterm.includeStandardAdditions = true

const id = iterm.currentWindow().id();
console.log(id);
```

**Comment by travsten** [comment]
@briangonzalez it looks like it still isn't recognizing my current window...here is what I did, and the output...

`mathiasravsten mert (master) $ node
> const jxa = require('jxa');
undefined
> const Application = jxa.Application;
undefined
> const iterm = Application('iterm');
undefined
> iterm.includeStandardAdditions = true;
true
> const id = iterm.currentWindow().id();
TypeError: Cannot read property 'id' of undefined
    at repl:1:33
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:191:7)
    at REPLServer.Interface._onLine (readline.js:241:10)
    at REPLServer.Interface._line (readline.js:590:8)
>`

**Comment by briangonzalez** [comment]
And what about this from the command line?

```sh
$ osascript -e 'tell application "iTerm" to get current session of current tab of current window'
```

**Comment by travsten** [comment]
I actually just re-installed iTerm2. Solved the problem. Thought I did that already. Thanks for being available to help.

I had recently upgraded from iTerm2 version 2 to version 3. Maybe that is what messed that all up.

**Comment by varemenos** [comment]
I've just experienced this issue as well.
I think it has something to do with the dropdown terminal feature that iterm2 provides.

I can provide you with my iterm2 config file if needed.


I'm only experiencing this issue when using a launch_strategy (in_place||tab) though

**Comment by itsjustchioma** [comment]
I'm currently experiencing this problem and none of these solutions helped me 🥲
