### ISSUE TITLE
SyntaxError: Identifier 'configLoader' has already been declared

### ISSUE THREAD

**Issue by pcriv** [eggplanetio/mert#23]
```
/Users/pablocrivella/.config/fnm/lib/node_modules/mert/index.js:34
  const configLoader = require('./lib/config-loader.js');
  ^

SyntaxError: Identifier 'configLoader' has already been declared
    at Object.<anonymous> (/Users/pablocrivella/.config/fnm/lib/node_modules/mert/index.js:1:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

node version: 4.5.0
npm version: 2.15.9
shell: fish
- NOTE: Node installed using [fnm](https://github.com/fisherman/fnm) (fish node manager)

**Comment by briangonzalez** [comment]
Hi @pablocrivella – can you try upgrading to node > 6.2.0 and seeing if your issue goes away?

**Comment by pcriv** [comment]
It works with node v6.5.0 and npm 3.10.3, thanks!
